# Generated by Django 6.0.5 on 2026-05-24 11:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время посещения')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('cancelled', 'Отменено')], default='active', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clients.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL, verbose_name='Кто отметил')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='memberships.clientmembership', verbose_name='Абонемент')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-visit_datetime'],
            },
        ),
    ]
