# Generated by Django 6.0.5 on 2026-06-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_classregistration'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='class_registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='schedule.classregistration', verbose_name='Запись на занятие'),
        ),
        migrations.AddField(
            model_name='visit',
            name='fitness_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='schedule.fitnessclass', verbose_name='Занятие'),
        ),
    ]
