# Generated by Django 6.0.5 on 2026-06-07 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Стаж работы'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.CreateModel(
            name='TrainerClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата закрепления')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_trainer_client_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Кто закрепил')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_assignments', to='clients.client', verbose_name='Клиент')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='trainers.trainer', verbose_name='Тренер')),
            ],
            options={
                'verbose_name': 'Клиент тренера',
                'verbose_name_plural': 'Клиенты тренеров',
                'ordering': ['trainer__full_name', 'client__full_name'],
                'unique_together': {('trainer', 'client')},
            },
        ),
    ]
