# Generated by Django 6.0.5 on 2026-05-24 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Длительность, дней')),
                ('visit_limit', models.PositiveIntegerField(verbose_name='Количество посещений')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Тип абонемента',
                'verbose_name_plural': 'Типы абонементов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('remaining_visits', models.PositiveIntegerField(verbose_name='Остаток посещений')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Истек'), ('completed', 'Завершен'), ('frozen', 'Заморожен'), ('cancelled', 'Отменен')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clients.client', verbose_name='Клиент')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_memberships', to='memberships.membershiptype', verbose_name='Тип абонемента')),
            ],
            options={
                'verbose_name': 'Абонемент клиента',
                'verbose_name_plural': 'Абонементы клиентов',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
