# Generated by Django 6.0.5 on 2026-05-24 12:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата записи')),
                ('status', models.CharField(choices=[('registered', 'Записан'), ('cancelled', 'Отменен'), ('visited', 'Посетил'), ('missed', 'Не пришел')], default='registered', max_length=20, verbose_name='Статус записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_registrations', to='clients.client', verbose_name='Клиент')),
                ('fitness_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='schedule.fitnessclass', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Запись на занятие',
                'verbose_name_plural': 'Записи на занятия',
                'ordering': ['-registration_date'],
                'unique_together': {('fitness_class', 'client')},
            },
        ),
    ]
